### ISSUE TITLE
wget GPG error

### ISSUE THREAD

**Issue by Ads20000** [baedert/corebird-xdg-app#1]
Using Flatpak 0.6.11 (the version in Ubuntu 16.10) I can't use the automatic repository install command (will try with Flatpak 0.6.13 from the PPA later). However, I can't use the manual method either, Terminal output below:
<pre><code>$ wget https://baedert.org/repo/baedert-repo.gpg
--2016-11-09 15:31:50--  https://baedert.org/repo/baedert-repo.gpg
Resolving baedert.org (baedert.org)... 84.38.64.56
Connecting to baedert.org (baedert.org)|84.38.64.56|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-09 15:31:51 ERROR 404: Not Found.</code></pre>

**Comment by baedert** [comment]
Was just a missing file... :|
