### ISSUE TITLE
Video Playback Doesn't Work

### ISSUE THREAD

**Issue by nedrichards** [baedert/corebird-xdg-app#10]
When pressing on a video in the stream I get a popup with the following error.

> gsturidecodebin.c(1006): no_more_pads_full (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin1:
> no suitable plugins found:
> gstdecodebin2.c(4565): gst_decode_bin_expose (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin1/GstDecodeBin:decodebin1:
> no suitable plugins found:
> Missing decoder: MPEG-4 AAC (audio/mpeg, framed=(boolean)true, mpegversion=(int)4, level=(string)2, base-profile=(string)lc, profile=(string)lc, rate=(int)48000, channels=(int)2, stream-format=(string)adts)
> Missing decoder: H.264 (video/x-h264, stream-format=(string)byte-stream, alignment=(string)nal, parsed=(boolean)true)

My device should have AAC and H264 decoding enabled in GStreamer (certainly it works outside the sandbox). This is on Endless OS 3.1, I'll have a little dig further.

**Comment by baedert** [comment]
Are you using the stable or the nightly version? I've just updated the stable one to build `gst-libav` as well and that makes it work in a quick test, but I've not stumbled upon the mpeg4 error message, only the h.264 one.

**Comment by nedrichards** [comment]
I was using stable. That update makes everything I can find work. Will reopen if I find anything else, thanks!
