### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by Ads20000** [baedert/corebird-xdg-app#2]
Perhaps something of a feature request, but a launcher should be added to the application menu of the distribution so that Corebird doesn't have to be launched from Terminal or manually added as a launcher.

**Comment by baedert** [comment]
After logging out once (after installing flatpak), the flatpak dir for .desktop files should be added to your $XDG_DATA_DIRS and your launcher should find it. Provided that it cares about that directory at all (and .desktop files). There's nothing for individual applications to do here.

**Comment by Ads20000** [comment]
Oh sorry, yes you're absolutely right. Bit counterintuitive that you have to log out but I suppose that's just a limitation of Flatpak.
