### ISSUE TITLE
Corebird cant open default Browser

### ISSUE THREAD

**Issue by onsc** [baedert/corebird-xdg-app#5]
When i try to get pin, nothing happens. Cant use Corebird. As a default browser that i wait to be open Opera,Firefox or Chrome. Here logs and system informations; ( only start information on syslog )

`(corebird:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(corebird:2): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(corebird:2): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(corebird:2): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.
`

system info:

Description:	Ubuntu 16.04.1 LTS
4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Thank you.

**Comment by baedert** [comment]
And do you have `xdg-desktop-portal` and `xdg-desktop-portal-gtk` installed like the readme mentions?

**Comment by onsc** [comment]
i missed that line. Sorry. i will try to install those libraries. I think i dont have. Please delete this issue :( if i cant open again, i can recreate.
