### ISSUE TITLE
16.04 Browser not opening.

### ISSUE THREAD

**Issue by onsc** [baedert/corebird-xdg-app#6]
This is my second issue report. Sorry for the first. Because i hadnt installed xdg-desktop-portal and xdg-desktop-portal-gtk

Now, i installed those libraries by adding yakkety repository to my sources list. But it is still not opening. Has anyone tried to use this flatpak on Ubuntu 16.04? And what was the steps? It may help others.

**Comment by baedert** [comment]
Is there any output on the console or in the journal when you click a link and nothing happens?

**Comment by onsc** [comment]
nothing shows : 
`flatpak run org.baedert.corebird 

(corebird:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(corebird:2): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(corebird:2): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:225:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:231:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:232:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:2): Gtk-WARNING **: Theme parsing error: style.css:237:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:2): corebird-CRITICAL **: AccountCreateWidget.vala:87: Authorization Required

`
at the end of log i wrote any pin and pressed confirm.

syslog :

systemd[2373]: Started flatpak-org.baedert.corebird-1443.scope.

**Comment by baedert** [comment]
What's in the journal when you do that? The console output alone doesn't say much unfortunately. Unless you want to build https://github.com/matthiasclasen/portal-test yourself I'm out of ideas.

**Comment by onsc** [comment]
That was weird but i reinstalled flatpak-builder. now it is working.... i think it is more related to Ubuntu installing packages or ppa. Thank you for this flatpak.
