### ISSUE TITLE
Can't remove Corebird

### ISSUE THREAD

**Issue by Ads20000** [baedert/corebird-xdg-app#7]
```
$ flatpak list
org.baedert.corebird
$ flatpak uninstall org.baedert.corebird
error: org.baedert.corebird master not installed
```

Perhaps I'm not understanding something about Flatpak.

**Comment by baedert** [comment]
Perhaps you installed it with `--user` and now you're not passing that when uninstalling.

**Comment by Ads20000** [comment]
Oh, you're right, will close the issue, but first can you tell me what does --user do? :)

**Comment by baedert** [comment]
As far as I know that just means it will only be accessible by the user who installed it, as opposed to a system-wide installation, which happens without `--user`. The practical difference is also that `--user` doesn't require you to type in your root password which is a little nicer.

**Comment by Ads20000** [comment]
Nice, thanks!
